

GET http://localhost:3000/api/produtos
Content-Type: application/json
###


POST http://localhost:3000/api/produtos
Content-Type: application/json

{
"nome": "pimento",
"estoque": 80,
"valor": "20,35"
}
###


# Alterar usuário
PUT http://localhost:3000/api/produtos
Content-Type: application/json

{
 "_id": "5f6cba8798eca62ccce84ba7",
 "nome": "pimenta",
"estoque": 80,
"preco": "20,35"
}
###


# Excluir um usuário
DELETE http://localhost:3000/api/produtos/5f5a96dd5e818fae8fc6e1db
Content-Type: application/json
###


# Obter pelo id de usuário
GET http://localhost:3000/api/produtos/5f6cb80e07cee54810920f5f
Content-Type: application/json
###


# Obter usuários filtrando
GET http://localhost:3000/api/produtos/filtro/pastel
Content-Type: application/json
###